services:
  web: # Defines a service named 'web'.
    image: simpleweb-web:latest
    command: npm run start # Overrides the default command specified in the Dockerfile.
    ports:
      - "3000:3000" # Maps port 3000 on your host machine to port 3000 in the Docker container.
